### ISSUE TITLE
Docker image does not build (Apple M1)

### ISSUE THREAD

**Issue by val-ismaili** [arup-group/osmox#34]
On building a docker image on an Apple M1 machine with:
`docker build -t "osmox" .`

when executing this [line](https://github.com/arup-group/osmox/blob/552510ee668124594f5abcbb835d2b10c119e4e3/Dockerfile#L13) in the dockerfile I get the error:

```
`× python setup.py egg_info did not run successfully.
#10 2.642   │ exit code: 1
#10 2.642   ╰─> [12 lines of output]
#10 2.642       Failed `CDLL(libgeos_c.so.1)`
#10 2.642       Failed `CDLL(libgeos_c.so)`
#10 2.642       Traceback (most recent call last):
#10 2.642         File "<string>", line 36, in <module>
#10 2.642         File "<pip-setuptools-caller>", line 34, in <module>
#10 2.642         File "/tmp/pip-install-w53lhwgs/shapely_248fa231557d464fa86b92b4ff842582/setup.py", line 74, in <module>
#10 2.642           from shapely._buildcfg import geos_version_string, geos_version, \
#10 2.642         File "/tmp/pip-install-w53lhwgs/shapely_248fa231557d464fa86b92b4ff842582/shapely/_buildcfg.py", line 167, in <module>
#10 2.642           fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
#10 2.642         File "/tmp/pip-install-w53lhwgs/shapely_248fa231557d464fa86b92b4ff842582/shapely/_buildcfg.py", line 161, in load_dll
#10 2.642           libname, fallbacks or []))
#10 2.642       OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
#10 2.642       [end of output]
#10 2.642   
#10 2.642   note: This error originates from a subprocess, and is likely not a problem with pip.
#10 2.643 error: metadata-generation-failed`
```

**Comment by val-ismaili** [comment]
Docker image will build if add the below to dockerfile:
```
apt-get -y install libgeos-dev &&  \
apt-get -y install libgdal-dev &&  \
apt-get -y install build-essential cmake libboost-dev libexpat1-dev zlib1g-dev libbz2-dev &&  \
```

**Comment by brynpickering** [comment]
With the new mamba install method, this has a workaround on Apple Silicon devices: https://github.com/arup-group/genet/issues/221
